<?php
/***
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Magento Extensions
 * @package    Toonvd_Recentlyviewed
 * @copyright  Copyright (c) 2016 Toon Van Dooren
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Toon Van Dooren <toon_vd@live.com>
 */
?>
<script type="text/javascript">
    var recentlyViewedConfig = {
        desiredScopeAndId: '<?php echo $this->getDesiredScopeAndId(); ?>',
        productId:<?php echo $this->getProductId(); ?>,
        maxLength:<?php echo $this->getMaxLength(); ?>,
        productInfo: {
            name: '<?php echo $this->getProductName(); ?>',
            url: '<?php echo $this->getProductUrl(); ?>',
            imageUrl: '<?php echo $this->getProductImage(); ?>'
        }
    };
    new Toonvd.Recentlyviewed("recently-viewed-listitem", recentlyViewedConfig);
</script>
