<?php
/***
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Magento Extensions
 * @package    Toonvd_Recentlyviewed
 * @copyright  Copyright (c) 2016 Toon Van Dooren
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Toon Van Dooren <toon_vd@live.com>
 */
?>
<?php
$_item = $this->getCurrentProduct();
$desiredScopeAndId = $this->getDesiredScopeAndId();
$maxLength = $this->getMaxLength();
?>
<div class="recently-viewed-listitem" id="recently-viewed-listitem" style="display:none;">
    <li class="item">
        <a href="<?php echo $this->getProductUrl() ?>">
            <span class="product-image"><img src="<?php echo $this->getProductImage(); ?>"
                                             width="50" height="50"
                                             alt="<?php echo $this->escapeHtml($this->getProductName()) ?>"/></span>
        </a>

        <div class="product-details">
            <p class="product-name">
                <a href="<?php echo $this->getProductUrl() ?>">
                    <?php echo $this->getProductName() ?>
                </a>
            </p>
        </div>
    </li>
</div>
<script type="text/javascript">
    var recentlyViewedConfig = {
        desiredScopeAndId: "<?php echo $desiredScopeAndId ?>",
        productId:<?php echo $this->getProductId(); ?>,
        maxLength:<?php echo $maxLength ?>
    };
    new Toonvd.Recentlyviewed("recently-viewed-listitem", recentlyViewedConfig);
</script>
