<?php
/***
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Magento Extensions
 * @package    Toonvd_Recentlyviewed
 * @copyright  Copyright (c) 2016 Toon Van Dooren
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Toon Van Dooren <toon_vd@live.com>
 */
?>
<div class="block block-list block-viewed" id="recently-viewed" style="display:none;">
    <div class="block-title">
        <strong><span><?php echo $this->getListBlockTitle() ?></span></strong>
    </div>
    <div class="block-content">
        <ol id="recently-viewed-items" class="mini-products-list">
        </ol>
    </div>
</div>
<script type="text/javascript">
    var recentlyViewedConfig = {desiredScopeAndId: "<?php echo $this->getDesiredScopeAndId() ?>"};
    new Toonvd.Recentlyviewed("recently-viewed", recentlyViewedConfig);
    decorateList("recently-viewed-items");
</script>